/* Allwin Marbles — i18n dictionary (flat keys), ported from the original design. */
export type Lang = "en" | "ar";

export const I18N: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.products": "Products", "nav.projects": "Projects",
    "nav.about": "About", "nav.heritage": "Heritage", "nav.contact": "Contact",
    "nav.callNow": "Call Now", "nav.language": "Language", "nav.enquire": "Enquire",
    "brand.sub": "Since 1985",

    "home.tagline": "Exporter · Manufacturer · Designer — Since 1985",
    "home.heroTitle": "Allwin Marbles",
    "home.heroLine": "The same Makrana stone that built the Taj Mahal —\nquarried, carved and exported for four decades.",
    "home.scroll": "Scroll to explore",
    "home.introEyebrow": "From Makrana to the World",
    "home.introTitle": "Stone with a soul, shaped by four generations of hands.",
    "home.introBody": "Established in 1985 in the marble city of Makrana, Rajasthan, Allwin Marbles unites deep quarry knowledge with master craftsmanship — supplying and installing the world's finest natural stone for homes, hotels, temples and mosques across India and the globe.",
    "home.stat1": "Founded", "home.stat1v": "1985",
    "home.stat2": "Years of craft", "home.stat2v": "40",
    "home.stat3": "Marble & granite varieties", "home.stat3v": "60",
    "home.stat4": "Reach", "home.stat4v": "Global",
    "home.galleryEyebrow": "Selected Work",
    "home.galleryTitle": "Where stone becomes architecture",
    "home.gallerySub": "A living portfolio across the disciplines we are known for — from monumental fountains to hand-inlaid floors.",
    "home.seeMore": "See More", "home.seeLess": "See Less", "home.shown": "shown", "home.viewAll": "View full portfolio",
    "home.ctaEyebrow": "Let's build something timeless",
    "home.ctaTitle": "Bring your vision to our quarry.",
    "home.ctaBody": "Tell us about your project — residential, commercial, religious or heritage — and our team will guide you from stone selection to final polish.",
    "home.ctaBtn": "Start an enquiry",

    "cat.floor": "Floor", "cat.fountain": "Fountain", "cat.handCraft": "Hand Craft",
    "cat.inlay": "Inlay", "cat.masjid": "Masjid", "cat.stair": "Stair", "cat.table": "Table",

    "products.eyebrow": "Our Collection",
    "products.title": "Products & Services",
    "products.subtitle": "From raw Makrana marble slabs to handcrafted masterpieces and large-scale construction — every surface, sourced and finished in-house.",
    "products.marble": "Marble & Stone", "products.granite": "Granite",
    "products.cultured": "Cultured Marble", "products.mosaic": "Mosaic Tiles",
    "products.quartz": "Sparkle Quartz", "products.handicrafts": "Handicrafts & Carving",
    "products.countLabel": "in this collection",

    "projects.eyebrow": "Portfolio",
    "projects.title": "Our Projects",
    "projects.subtitle": "A showcase of our craftsmanship — from intricate Islamic calligraphy and marble inlay to hand-carved sculpture and luxury home décor.",
    "projects.religious": "Religious", "projects.heritage": "Heritage", "projects.homeDecor": "Home Décor",

    "about.eyebrow": "Our Story",
    "about.title": "About Allwin Marbles",
    "about.fromMakrana": "From Makrana to the World",
    "about.story1": "Allwin Marble was established in 1985 by Mr. Abdul Hafeez Rander, bringing together deep knowledge of marble quarries and natural stone for residential and commercial projects.",
    "about.story2": "Through vast supply and export, the company gained expertise in domestic and international markets as a premier manufacturer and curator of marble.",
    "about.story3": "We provide the market with innovation, imagination and the opportunities of those who constantly seek to innovate.",
    "about.story4": "Makrana marble is legendary — it is the same stone used to build the Taj Mahal over 350 years ago.",
    "about.founderEyebrow": "The Founder",
    "about.founderName": "Mr. Abdul Hafeez Rander",
    "about.founderTitle": "Founder",
    "about.founderText": "By the grace of the Almighty, Allwin Marbles has won millions of hearts with outstanding work in houses, hotels, hospitals, and more.",
    "about.founderHistory": "We are grateful for the passionate, persistent hard work of our ancestors — especially the late Haji Faqir Mohd Rander, who explored all of India for marble and handicraft work. His journey began in 1904.",
    "about.companyOverview": "Company Overview",
    "about.founded": "Founded", "about.iec": "IEC", "about.location": "Location", "about.reach": "Reach",
    "about.reach2": "India & Global",
    "about.registrationDetails": "Registration Details",
    "about.iecNo": "IEC No", "about.gstinNo": "GSTIN No",
    "about.vision": "Our Vision",
    "about.visionText": "Our goal is to beautify every residential and commercial project in India and abroad. We dream of making the best marble and granite available right at your doorstep.",
    "about.visionQuote": "We ensure unvarying quality, unwavering commitment, and moral integrity.",
    "about.activities": "Our Activities",
    "about.activity1": "Supply of all kinds of Marble, Granite, Sandstone, Semi-Precious stones, Onyx, Quartzite, Slate and Limestone in different sizes and thicknesses.",
    "about.activity2": "Turnkey projects involving supply, fixing and polishing of stone in hotels, temples, commercial and residential complexes.",
    "about.activity3": "Stone carving projects with materials and on-site installation.",
    "about.activity4": "Manufacturing fine carved stone items to customer design and specification.",
    "about.activity5": "Finished stone slabs manufactured to your requirements.",
    "about.coreValues": "Our Core Values",
    "about.cv1Title": "Customer First", "about.cv1Desc": "We work diligently to adapt our systems to customer requirements.",
    "about.cv2Title": "Integrity in Action", "about.cv2Desc": "We are known as one of the most reliable, disciplined and responsible groups in the marble industry.",
    "about.cv3Title": "Excellent Teamwork", "about.cv3Desc": "We have a team of professionals — engineers, managers and technicians — with modern machinery.",
    "about.cv4Title": "Solutions Oriented", "about.cv4Desc": "We offer a comprehensive set of expertise, services and tools to realise your vision.",
    "about.assurances": "Our Assurances",
    "about.assurance1": "Very competitive pricing structure",
    "about.assurance2": "Proactive communication and rapid response",
    "about.assurance3": "Punctuality in execution of orders",
    "about.assurance4": "Accuracy in measurement of ordered goods",
    "about.assurance5": "Commitment to promises",
    "about.assurance6": "Tailored solutions for every project",

    "makrana.eyebrow": "Heritage",
    "makrana.title": "The Legacy of Makrana Marble",
    "makrana.subtitle": "One of the most sought-after ornamental stones on earth — present in the Taj Mahal, the Victoria Memorial, the Sheikh Zayed Mosque and countless palaces.",
    "makrana.epitome": "The Epitome of Versatility",
    "makrana.intro1": "Makrana sits in the Nagaur district of Rajasthan. Its marble is among the most preferred ornamental stones in the world.",
    "makrana.intro2": "The Taj Mahal of Agra and the Victoria Memorial of Kolkata are both clad in Makrana marble — two of history's most iconic monuments.",
    "makrana.intro3": "It has also been a major building material for scores of forts, palaces and archaeologically significant buildings.",
    "makrana.timelineTitle": "A Brief History",
    "makrana.h1y": "c. 1631", "makrana.history1": "The Taj Mahal becomes the first great monument to use Makrana marble. Artisans are believed to have travelled from the Mekran city of Iran.",
    "makrana.h2y": "17th C.", "makrana.history2": "The contractor Paharkhan dug a well at the quarry — one of the mining ranges, Paharkua, still bears his name.",
    "makrana.h3y": "1906", "makrana.history3": "The Victoria Memorial is built by Martin Burn & Company, which installed an Italian gang-saw and a steam-operated jib crane.",
    "makrana.h4y": "Modern", "makrana.history4": "Diamond gang-saw machines revolutionise marble processing in Makrana, enabling precision at scale.",
    "makrana.miningRanges": "Prominent Mining Ranges",
    "makrana.marbleTypes": "Types of Makrana Marble",
    "makrana.marbleTypesSub": "Makrana marble splits into distinct categories by design and pattern.",
    "makrana.propertiesTitle": "Properties & Applications",
    "makrana.properties1": "Makrana marble holds a unique place in the heritage of stone for its visual appeal and mono-mineralic purity.",
    "makrana.properties2": "It is perhaps the finest marble available anywhere, with 95–98% calcium carbonate content.",
    "makrana.geological": "Geological Setup",
    "makrana.geo1": "Rajasthan has a highly varied, complex geology. Makrana deposits belong to the Ajmer Formation of the Kumbhalgarh Group.",
    "makrana.geo2": "The Raialo Series comprises limestones frequently metamorphosed to marble.",
    "makrana.geo3": "Marble reserves in the region are estimated at 55 million tonnes.",
    "makrana.statReserves": "Reserves", "makrana.statReservesV": "55M tonnes",
    "makrana.statPurity": "Calcium carbonate", "makrana.statPurityV": "95–98%",
    "makrana.statRanges": "Mining ranges", "makrana.statRangesV": "14+",

    "mr1": "Paharkuan — White Albeta", "mr2": "Kolha Dungri", "mr3": "Dungri",
    "mr4": "Chak Dungri — Adanga", "mr5": "Sahabwali — Albeta", "mr6": "Bhot — Adanga",
    "mr7": "Matabar", "mr8": "Ulodi — Adanga Pink", "mr9": "Nahar", "mr10": "Kumhari",
    "mr11": "Rawat Dungri Adanga", "mr12": "Chaurasa — White", "mr13": "Boarwad", "mr14": "Gunawati",

    "mt1n": "Makrana White", "mt1d": "Widely used in homes, temples, mosques and monuments — 95–98% calcium carbonate.",
    "mt2n": "Albeta", "mt2d": "A calcite stone; milky white, also found in grey and panther-brown patterns.",
    "mt3n": "Dungri", "mt3d": "One of the oldest, finest grades — no chemical reinforcement, no colour change, no pin-holes.",
    "mt4n": "Chak Dungri", "mt4d": "From the Chak Dungri–Adanga range, known for subtle veining and excellent durability.",
    "mt5n": "Khumari", "mt5d": "A grey marble with elegant patterning from the Kumhari range.",
    "mt6n": "Makrana Pink", "mt6d": "Distinctive pink marble, popular for flooring, elevations and decorative work.",
    "mt7n": "Pink Adanga", "mt7d": "Pink marble with unique patterns from the Ulodi–Adanga range.",
    "mt8n": "Adanga", "mt8d": "Varies grey to brown, sourced across multiple mining ranges.",

    "contact.eyebrow": "Get In Touch",
    "contact.title": "Contact & Enquiries",
    "contact.subtitle": "Interested in our products or services? Send an enquiry and we'll respond within 24 hours.",
    "contact.yourName": "Your Name", "contact.emailAddress": "Email Address",
    "contact.phoneNumber": "Phone Number", "contact.productInterest": "Product of Interest",
    "contact.marbleGranite": "Marble & Granite Slabs", "contact.handicrafts": "Handicrafts & Carving",
    "contact.construction": "Construction Projects", "contact.other": "Other",
    "contact.yourMessage": "Your Message", "contact.sending": "Sending…", "contact.sendEnquiry": "Send Enquiry",
    "contact.successTitle": "Enquiry sent",
    "contact.successMessage": "Thank you — we'll get back to you shortly.",
    "contact.sendAnother": "Send another enquiry",
    "contact.nameRequired": "Name is required", "contact.emailRequired": "Email is required",
    "contact.emailInvalid": "Please enter a valid email", "contact.messageRequired": "Message is required",
    "contact.companyName": "Allwin Marbles",
    "contact.visit": "Visit / Write", "contact.call": "Call Us", "contact.email": "Email Us",
    "contact.whatsapp": "Chat on WhatsApp", "contact.reply": "We reply within 24 hours",
    "contact.makrana": "Makrana, Rajasthan", "contact.kerala": "Palakkad, Kerala",
    "contact.errorMessage": "Failed to send. Please try again.",

    "footer.desc": "Since 1985, crafting elegance in stone. Supplier of premium Makrana marble, granite, handicrafts and complete stone solutions.",
    "footer.quickLinks": "Explore", "footer.contact": "Contact",
    "footer.copyright": "All rights reserved.",
    "footer.makranaLocation": "Near Bhati Petrol Pump, Bye Pass Road, Makrana, Rajasthan — 341505",
    "footer.keralaLocation": "Allwin Marbles & Granite, Palakkad, Kerala — 673304",
    "footer.craft": "Crafted with care",
  },

  ar: {
    "nav.home": "الرئيسية", "nav.products": "المنتجات", "nav.projects": "المشاريع",
    "nav.about": "من نحن", "nav.heritage": "التراث", "nav.contact": "اتصل بنا",
    "nav.callNow": "اتصل الآن", "nav.language": "اللغة", "nav.enquire": "استفسار",
    "brand.sub": "منذ ١٩٨٥",

    "home.tagline": "مُصدِّر · مُصنِّع · مُصمِّم — منذ ١٩٨٥",
    "home.heroTitle": "آلوين للرخام",
    "home.heroLine": "نفس رخام مكرانا الذي بُني به تاج محل —\nنستخرجه وننحته ونصدّره منذ أربعة عقود.",
    "home.scroll": "مرّر للاستكشاف",
    "home.introEyebrow": "من مكرانا إلى العالم",
    "home.introTitle": "حجرٌ بروح، تشكّله أيدي أربعة أجيال.",
    "home.introBody": "تأسست آلوين للرخام عام ١٩٨٥ في مدينة الرخام مكرانا براجستان، لتجمع بين المعرفة العميقة بالمحاجر وحرفية الأساتذة — نورّد ونركّب أرقى الأحجار الطبيعية للمنازل والفنادق والمعابد والمساجد في الهند والعالم.",
    "home.stat1": "تأسست", "home.stat1v": "١٩٨٥",
    "home.stat2": "عاماً من الحرفة", "home.stat2v": "٤٠",
    "home.stat3": "أصناف الرخام والجرانيت", "home.stat3v": "٦٠",
    "home.stat4": "النطاق", "home.stat4v": "عالمي",
    "home.galleryEyebrow": "أعمال مختارة",
    "home.galleryTitle": "حين يصبح الحجر عمارة",
    "home.gallerySub": "معرض حيّ عبر التخصصات التي نُعرف بها — من النوافير الضخمة إلى الأرضيات المرصّعة يدوياً.",
    "home.seeMore": "المزيد", "home.shown": "معروضة", "home.viewAll": "عرض المعرض الكامل",
    "home.ctaEyebrow": "لنصنع شيئاً خالداً",
    "home.ctaTitle": "أحضر رؤيتك إلى محجرنا.",
    "home.ctaBody": "أخبرنا عن مشروعك — سكني أو تجاري أو ديني أو تراثي — وسيرافقك فريقنا من اختيار الحجر حتى التلميع النهائي.",
    "home.ctaBtn": "ابدأ استفساراً",

    "cat.floor": "الأرضيات", "cat.fountain": "النوافير", "cat.handCraft": "الحرف اليدوية",
    "cat.inlay": "الترصيع", "cat.masjid": "المسجد", "cat.stair": "السلالم", "cat.table": "الطاولات",

    "products.eyebrow": "مجموعتنا",
    "products.title": "المنتجات والخدمات",
    "products.subtitle": "من ألواح رخام مكرانا الخام إلى التحف اليدوية والمشاريع الكبيرة — كل سطح، مصدره وتشطيبه عندنا.",
    "products.marble": "الرخام والحجر", "products.granite": "الجرانيت",
    "products.cultured": "الرخام المصنّع", "products.mosaic": "بلاط الموزاييك",
    "products.quartz": "الكوارتز اللامع", "products.handicrafts": "الحرف والنحت",
    "products.countLabel": "في هذه المجموعة",

    "projects.eyebrow": "معرض الأعمال",
    "projects.title": "مشاريعنا",
    "projects.subtitle": "عرض لحرفنا — من الخط العربي الإسلامي والترصيع الرخامي إلى المنحوتات اليدوية وديكور المنزل الفاخر.",
    "projects.religious": "ديني", "projects.heritage": "تراث", "projects.homeDecor": "ديكور المنزل",

    "about.eyebrow": "قصتنا",
    "about.title": "عن آلوين للرخام",
    "about.fromMakrana": "من مكرانا إلى العالم",
    "about.story1": "تأسست آلوين للرخام عام ١٩٨٥ على يد السيد عبد الحفيظ راندر، لتجمع المعرفة العميقة بمحاجر الرخام والحجر الطبيعي للمشاريع السكنية والتجارية.",
    "about.story2": "من خلال التوريد والتصدير الواسع، اكتسبت الشركة خبرة في الأسواق المحلية والدولية كشركة رائدة في تصنيع الرخام.",
    "about.story3": "نوفّر للسوق الابتكار والخيال والفرص لمن يسعى باستمرار للتجديد.",
    "about.story4": "رخام مكرانا أسطوري — إنه نفس الحجر المستخدم في بناء تاج محل منذ أكثر من ٣٥٠ عاماً.",
    "about.founderEyebrow": "المؤسس",
    "about.founderName": "السيد عبد الحفيظ راندر",
    "about.founderTitle": "المؤسس",
    "about.founderText": "بفضل الله، فازت آلوين للرخام بملايين القلوب بأعمال متميزة في المنازل والفنادق والمستشفيات والمزيد.",
    "about.founderHistory": "نحن ممتنون للعمل الشغوف والمثابر لأسلافنا، خاصة المرحوم حاج فقير محمد راندر، الذي استكشف الهند بحثاً عن الرخام والحرف. بدأت رحلته عام ١٩٠٤.",
    "about.companyOverview": "نظرة على الشركة",
    "about.founded": "تأسست", "about.iec": "رمز التصدير", "about.location": "الموقع", "about.reach": "النطاق",
    "about.reach2": "الهند والعالم",
    "about.registrationDetails": "تفاصيل التسجيل",
    "about.iecNo": "رمز الاستيراد والتصدير", "about.gstinNo": "رقم GSTIN",
    "about.vision": "رؤيتنا",
    "about.visionText": "هدفنا تجميل كل مشروع سكني وتجاري في الهند وخارجها. نحلم بإتاحة أفضل الرخام والجرانيت عند بابك.",
    "about.visionQuote": "نضمن جودة ثابتة والتزاماً راسخاً ونزاهة أخلاقية.",
    "about.activities": "أنشطتنا",
    "about.activity1": "توريد جميع أنواع الرخام والجرانيت والحجر الرملي والأحجار الكريمة والأونيكس والكوارتزيت والأردواز والجير بمقاسات وسماكات مختلفة.",
    "about.activity2": "مشاريع تسليم مفتاح تشمل التوريد والتركيب والتلميع في الفنادق والمعابد والمجمعات التجارية والسكنية.",
    "about.activity3": "مشاريع نحت الحجر مع المواد والتركيب في الموقع.",
    "about.activity4": "تصنيع عناصر حجرية منحوتة حسب تصميم العميل ومواصفاته.",
    "about.activity5": "ألواح حجرية نهائية مصنوعة حسب متطلباتك.",
    "about.coreValues": "قيمنا الأساسية",
    "about.cv1Title": "العميل أولاً", "about.cv1Desc": "نعمل بجد لتكييف أنظمتنا وفق متطلبات العميل.",
    "about.cv2Title": "النزاهة في العمل", "about.cv2Desc": "نُعرف بأننا من أكثر المجموعات موثوقية وانضباطاً ومسؤولية في صناعة الرخام.",
    "about.cv3Title": "عمل جماعي متميز", "about.cv3Desc": "لدينا فريق من المهندسين والمدراء والتقنيين مع آليات حديثة.",
    "about.cv4Title": "موجّه نحو الحلول", "about.cv4Desc": "نقدّم مجموعة شاملة من الخبرات والخدمات والأدوات لتحقيق رؤيتك.",
    "about.assurances": "ضماناتنا",
    "about.assurance1": "هيكل تسعير تنافسي للغاية",
    "about.assurance2": "تواصل استباقي واستجابة سريعة",
    "about.assurance3": "الالتزام بمواعيد تنفيذ الطلبات",
    "about.assurance4": "الدقة في قياس البضائع المطلوبة",
    "about.assurance5": "الالتزام بالوعود",
    "about.assurance6": "حلول مخصصة لكل مشروع",

    "makrana.eyebrow": "التراث",
    "makrana.title": "إرث رخام مكرانا",
    "makrana.subtitle": "من أكثر الأحجار الزخرفية طلباً على الأرض — حاضر في تاج محل ومبنى فكتوريا وجامع الشيخ زايد وقصور لا تُحصى.",
    "makrana.epitome": "تجسيد التنوّع",
    "makrana.intro1": "تقع مكرانا في منطقة ناجور براجستان، ورخامها من أكثر الأحجار الزخرفية تفضيلاً في العالم.",
    "makrana.intro2": "تاج محل في أغرة ومبنى فكتوريا في كولكاتا كلاهما مكسوّان برخام مكرانا — اثنان من أشهر معالم التاريخ.",
    "makrana.intro3": "كان أيضاً مادة بناء رئيسية لعشرات القلاع والقصور والمباني الأثرية.",
    "makrana.timelineTitle": "تاريخ موجز",
    "makrana.h1y": "حوالي ١٦٣١", "makrana.history1": "يصبح تاج محل أول نصب عظيم يستخدم رخام مكرانا. يُعتقد أن الحرفيين قدموا من مدينة مكران الإيرانية.",
    "makrana.h2y": "القرن ١٧", "makrana.history2": "حفر المقاول بهارخان بئراً في المحجر — وما زال أحد نطاقات التعدين، بهاركوا، يحمل اسمه.",
    "makrana.h3y": "١٩٠٦", "makrana.history3": "يُبنى مبنى فكتوريا على يد شركة Martin Burn، التي ثبّتت منشار غانغ إيطالياً ورافعة بخارية.",
    "makrana.h4y": "العصر الحديث", "makrana.history4": "تُحدث مناشير الغانغ الماسية ثورة في معالجة الرخام في مكرانا، وتتيح الدقة على نطاق واسع.",
    "makrana.miningRanges": "أبرز نطاقات التعدين",
    "makrana.marbleTypes": "أنواع رخام مكرانا",
    "makrana.marbleTypesSub": "ينقسم رخام مكرانا إلى فئات مميزة حسب التصميم والنمط.",
    "makrana.propertiesTitle": "الخصائص والتطبيقات",
    "makrana.properties1": "يحتل رخام مكرانا مكانة فريدة في تراث الحجر لجاذبيته البصرية ونقائه أحادي المعدن.",
    "makrana.properties2": "ربما يكون أفضل رخام متاح في أي مكان، بنسبة كربونات كالسيوم ٩٥–٩٨٪.",
    "makrana.geological": "الإعداد الجيولوجي",
    "makrana.geo1": "تتمتع راجستان بجيولوجيا متنوعة ومعقّدة. تنتمي رواسب مكرانا إلى تكوين أجمر من مجموعة كومبهالغار.",
    "makrana.geo2": "تتكوّن سلسلة رايالو من حجر جيري يتحوّل غالباً إلى رخام.",
    "makrana.geo3": "تُقدّر احتياطيات الرخام في المنطقة بـ ٥٥ مليون طن.",
    "makrana.statReserves": "الاحتياطي", "makrana.statReservesV": "٥٥ م طن",
    "makrana.statPurity": "كربونات الكالسيوم", "makrana.statPurityV": "٩٥–٩٨٪",
    "makrana.statRanges": "نطاقات التعدين", "makrana.statRangesV": "+١٤",

    "mr1": "بهاركوان — ألبيتا الأبيض", "mr2": "كولا دونغري", "mr3": "دونغري",
    "mr4": "تشاك دونغري — أدانغا", "mr5": "ساهابوالي — ألبيتا", "mr6": "بهوت — أدانغا",
    "mr7": "ماتابار", "mr8": "أولودي — أدانغا الوردي", "mr9": "نهار", "mr10": "كومهاري",
    "mr11": "راوات دونغري أدانغا", "mr12": "تشوراسا — أبيض", "mr13": "بورواد", "mr14": "غوناواتي",

    "mt1n": "مكرانا الأبيض", "mt1d": "مستخدم على نطاق واسع في المنازل والمعابد والمساجد والنصب — ٩٥–٩٨٪ كربونات كالسيوم.",
    "mt2n": "ألبيتا", "mt2d": "حجر كالسيت؛ أبيض حليبي، ويتوفر بالرمادي والبني.",
    "mt3n": "دونغري", "mt3d": "من أقدم وأرقى الدرجات — بلا معالجة كيميائية ولا تغيّر لون ولا ثقوب.",
    "mt4n": "تشاك دونغري", "mt4d": "من نطاق تشاك دونغري–أدانغا، معروف بعروقه الدقيقة ومتانته الممتازة.",
    "mt5n": "كومهاري", "mt5d": "رخام رمادي بأنماط أنيقة من نطاق كومهاري.",
    "mt6n": "مكرانا الوردي", "mt6d": "رخام وردي مميز، شائع للأرضيات والواجهات والأعمال الزخرفية.",
    "mt7n": "أدانغا الوردي", "mt7d": "رخام وردي بأنماط فريدة من نطاق أولودي–أدانغا.",
    "mt8n": "أدانغا", "mt8d": "يتدرّج من الرمادي إلى البني، مصدره نطاقات تعدين متعددة.",

    "contact.eyebrow": "تواصل معنا",
    "contact.title": "الاتصال والاستفسارات",
    "contact.subtitle": "مهتم بمنتجاتنا أو خدماتنا؟ أرسل استفساراً وسنرد خلال ٢٤ ساعة.",
    "contact.yourName": "اسمك", "contact.emailAddress": "البريد الإلكتروني",
    "contact.phoneNumber": "رقم الهاتف", "contact.productInterest": "المنتج المهتم به",
    "contact.marbleGranite": "ألواح الرخام والجرانيت", "contact.handicrafts": "الحرف والنحت",
    "contact.construction": "مشاريع إنشائية", "contact.other": "أخرى",
    "contact.yourMessage": "رسالتك", "contact.sending": "جارٍ الإرسال…", "contact.sendEnquiry": "إرسال الاستفسار",
    "contact.successTitle": "تم إرسال الاستفسار",
    "contact.successMessage": "شكراً لك — سنعود إليك قريباً.",
    "contact.sendAnother": "إرسال استفسار آخر",
    "contact.nameRequired": "الاسم مطلوب", "contact.emailRequired": "البريد الإلكتروني مطلوب",
    "contact.emailInvalid": "يرجى إدخال بريد إلكتروني صحيح", "contact.messageRequired": "الرسالة مطلوبة",
    "contact.companyName": "آلوين للرخام",
    "contact.visit": "زرنا / راسلنا", "contact.call": "اتصل بنا", "contact.email": "راسلنا",
    "contact.whatsapp": "محادثة واتساب", "contact.reply": "نرد خلال ٢٤ ساعة",
    "contact.makrana": "مكرانا، راجستان", "contact.kerala": "بالاكاد، كيرالا",
    "contact.errorMessage": "فشل الإرسال. حاول مرة أخرى.",

    "footer.desc": "منذ ١٩٨٥، نصنع الأناقة في الحجر. مورّد رخام مكرانا الفاخر والجرانيت والحرف اليدوية وحلول الحجر المتكاملة.",
    "footer.quickLinks": "استكشف", "footer.contact": "اتصل بنا",
    "footer.copyright": "جميع الحقوق محفوظة.",
    "footer.makranaLocation": "بجانب مضخة بهاتي، طريق التجاوز، مكرانا، راجستان — ٣٤١٥٠٥",
    "footer.keralaLocation": "آلوين للرخام والجرانيت، بالاكاد، كيرالا — ٦٧٣٣٠٤",
    "footer.craft": "صُنع بعناية",
  },
};
